"""empty message

Revision ID: 4d450194f332
Revises: 540561d287ad
Create Date: 2018-01-11 12:40:40.571314

"""

# revision identifiers, used by Alembic.
revision = '4d450194f332'
down_revision = '540561d287ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'team')
    # ### end Alembic commands ###
