"""empty message

Revision ID: 540561d287ad
Revises: b13491f8b89a
Create Date: 2018-01-11 12:33:20.483948

"""

# revision identifiers, used by Alembic.
revision = '540561d287ad'
down_revision = 'b13491f8b89a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('game_master', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('plays_in', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'rooms', ['plays_in'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'plays_in')
    op.drop_column('users', 'game_master')
    # ### end Alembic commands ###
