"""empty message

Revision ID: b13491f8b89a
Revises: fb9e6cd6773b
Create Date: 2018-01-10 17:41:15.166042

"""

# revision identifiers, used by Alembic.
revision = 'b13491f8b89a'
down_revision = 'fb9e6cd6773b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('owner', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'owner')
    # ### end Alembic commands ###
