"""empty message

Revision ID: e6cc6d3ed652
Revises: b2e27a44d67b
Create Date: 2018-01-11 23:03:12.610069

"""

# revision identifiers, used by Alembic.
revision = 'e6cc6d3ed652'
down_revision = 'b2e27a44d67b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('to_play', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'to_play')
    # ### end Alembic commands ###
