"""empty message

Revision ID: fb9e6cd6773b
Revises: df688e550ebd
Create Date: 2018-01-10 12:31:51.992081

"""

# revision identifiers, used by Alembic.
revision = 'fb9e6cd6773b'
down_revision = 'df688e550ebd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('words_list', sa.JSON(), nullable=True))
    op.drop_column('rooms', 'words')
    op.drop_column('rooms', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('words', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'words_list')
    # ### end Alembic commands ###
